spring.application.name=ownlife
#spring.config.additional-location=optional:file:./config/application-local.properties
spring.config.import=optional:file:./config/application-local.properties
server.port=8081
server.address=0.0.0.0
file.upload-dir=C:/ownlife/uploads

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

openrouter.enabled=true
openrouter.api-url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=openai/gpt-oss-20b:free
openrouter.fallback-models=meta-llama/llama-3.2-3b-instruct:free,z-ai/glm-4.5-air:free
openrouter.site-url=http://localhost:8081
openrouter.app-name=OWN LIFE
openrouter.api-key=dummy
