spring.datasource.url=jdbc:mysql://ls-4968413b922797c9b85ff5fb698072c071b6a562.czgiqoag813n.ap-northeast-2.rds.amazonaws.com:3306/ownlife_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=dbmasteruser
spring.datasource.password=o}noOL0hl1~3~Dak<ut`PG1T-Yi`hO6J
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-init-sql=SET time_zone = '+09:00'

google_client_id=187585046787-kiurs1jq5jj2f1hji8hkm863lclsjsej.apps.googleusercontent.com
google_redirect_url=http://localhost:8081/login/google/auth
kakao_rest_api_key=c6c4b7426137cbbf24079714360dac9d
kakao_redirect_url=http://localhost:8081/login/kakao/auth
naver_client_id=j3xA9rHUQ1EaL03YnW4o
naver_client_secret=BsZlV7hoAg
naver_redirect_url=http://localhost:8081/login/naver/auth

openrouter.api-key=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
